tap "jesseduffield/lazygit"

brew "bash"
brew "eza"
brew "gh"
brew "gnupg"
brew "lazygit"
brew "neovim"
brew "pass"
brew "pinentry-mac"
brew "pipx"
brew "powerlevel10k"
brew "pyenv"
brew "pyenv-virtualenv"
brew "ripgrep"
brew "stow"
brew "tmux"
brew "ykman"
brew "zoxide"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

cask "codex"
cask "font-meslo-lg-nerd-font"
cask "wezterm"
